[project]
name = "agent-framework-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agent-framework>=1.0.0b251001",
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "jinja2>=3.1.6",
]

[tool.uv]
prerelease = "allow"
